Adding _id label to cluster admin, cluster proxy, cluster proxy CA expiry Timestamp, cluster proxy ca vlid and cluster id #93
openshift/osd-metrics-exporter pull request #95
Opened 2022-12-20 17:51 UTC by anispate

2022-12-22 18:28 UTC, mjlshen requested changes

2022-12-22 18:28 UTC, mjlshen commented on main.go
> +		MetricsAggregator: metrics.GetMetricsAggregator(clusterId),
Make sure all the reconcilers you added the `ClusterId` field to get populated, e.g.

```suggestion
		MetricsAggregator: metrics.GetMetricsAggregator(clusterId),
		ClusterId:                  clusterId,
```

2022-12-22 18:29 UTC, mjlshen commented
/hold
Can be reviewed, but is more straightfoward after #92 to merges in first. Please feel free to unhold this whenever

2023-01-10 13:35 UTC, T0MASD commented
/label tide/merge-method-squash

2023-01-24 17:57 UTC, zmird-r commented
Hi, I tested the operator and I confirm that the field` _id` is present for the `cluster_admin_enabled`, `cluster_proxy` and `cluster_id` metrics on my cluster.

```sh
[~ {stg} (zmird-qiu.oif6.s1:default)]$ curl --silent http://0.0.0.0:35000/metrics | grep cluster
# HELP cluster_admin_enabled Indicates if the cluster-admin role is enabled
# TYPE cluster_admin_enabled gauge
cluster_admin_enabled{_id="08e25af4-dede-4d59-b2df-7eeb819beb74",name="osd_exporter"} 0
# HELP cluster_id Indicates the cluster id
# TYPE cluster_id gauge
cluster_id{_id="08e25af4-dede-4d59-b2df-7eeb819beb74",name="osd_exporter"} 1
# HELP cluster_proxy Indicates cluster proxy state
# TYPE cluster_proxy gauge
cluster_proxy{_id="08e25af4-dede-4d59-b2df-7eeb819beb74",http="0",https="0",name="osd_exporter",trusted_ca="1"} 0
```

Thank you @T0MASD for the support.

2023-02-28 22:54 UTC, mjlshen commented
/unhold

2023-03-06 15:40 UTC, closed without merging